config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root to: 'creatives#index'
get 'creatives/index', to: 'creatives#index'
get 'creatives/show', to: 'creatives#show'

post 'creatives/create', to: 'creatives#create'
get 'creatives/ending', to: 'creatives#ending'
get 'creatives/all', to: 'creatives#all'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/request.rb
class Request < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/creatives_controller.rb
class CreativesController < ApplicationController
  layout "creative"

  def index
  end

  def show
    @user = User.new
  end

  def create
    @user = User.new
    @user.first_name = params[:user][:first_name]
    @user.last_name = params[:user][:last_name]
    @user.street = params[:user][:street]
    @user.location = params[:user][:location]
    @user.plz = params[:user][:plz]
    @user.email = params[:user][:email]
    @user.phone = params[:user][:phone]
    @user.request = params[:user][:request]
    @user.date_delivery = params[:user][:date_delivery]
    @user.save!
    redirect_to creatives_ending_path
  end

 def all
    @user = User.all
 end


  def ending
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :street, :location, :plz, :email, :request, :date_delivery, :phone)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/creatives/_bg_primary.html.erb
<section class="bg-primary" id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h2 class="section-heading">Ihr Gartenunterhalt ganz einfach!</h2>
                <hr class="light">
                <p class="text-faded">Hecken schneiden? Kiesweg jäten? Rosen einwintern? - Wir helfen Ihnen dabei! <br>
                Mit uns finden sie ganz einfach einen guten und preiswerten Gärtner. Mit Mapen erhalten sie verbindliche Offerten von qualifizerten Gärtnern aus der Region.   </p>
                <%= link_to "Offerte einholen", creatives_show_path, class: "btn btn-default btn-xl", :onclick => "return gtag_report_conversion()" %>

            </div>
        </div>
    </div>
</section>

app/views/creatives/_call_to_action.html.erb
<aside class="bg-dark">
    <div class="container text-center">
        <div class="call-to-action">
            <h2>Jetzt ganz einfach und unverbindlich Offerten einholen!</h2>
            <%= link_to "Offerte einholen", creatives_show_path, class: "btn btn-default btn-xl wow tada", :onclick => "return gtag_report_conversion()" %>
        </div>
    </div>
</aside>

app/views/creatives/_contact.html.erb
<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h2 class="section-heading">Kontaktieren Sie uns bei Fragen!</h2>
                <hr class="primary">
                <p>Haben sie Fragen wie unser Service funktioniert? Dann wenden sie Sich gerne per Email an uns und wir melden uns inner 24h gerne bei Ihnen! </p>
            </div>
            <div class="col-lg-4 col-lg-offset-2 text-center">
                <i class="fa fa-envelope fa-3x wow bounceIn"></i>
                <p>Seilergraben 41, 8001 Zürich</p>
            </div>
            <div class="col-lg-4 text-center">
                <i class="fa fa-envelope-o fa-3x wow bounceIn" data-wow-delay=".1s"></i>
                <p><a href="mailto:your-email@your-domain.com">fragen@mapen.ch</a></p>
            </div>
        </div>
    </div>
</section>

app/views/creatives/_header.html.erb
<header>
    <div class="header-content">
        <div class="header-content-inner">
            <h1>Finde deinen Gärtner in deiner Region </h1>
            <hr>
            <p>Sie erhalten kostenlos 5 Offerten mit Fixpreisen.
Schnell, sicher und transparent.</p>
            <%= link_to "Offerte einholen", creatives_show_path, class: "btn btn-primary btn-xl page-scroll", :onclick => "return gtag_report_conversion()" %>
        </div>
    </div>
</header>

app/views/creatives/_navbar.html.erb
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand page-scroll" href="#page-top">Mapen</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="page-scroll" href="#about">Offerte einholen</a>
                </li>
                <li>
                    <a class="page-scroll" href="#services">Dein Nutzen</a>
                </li>
                <li>
                    <a class="page-scroll" href="#contact">Kontakt</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/creatives/_offer.html.erb
<section id="services">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">Holen Sie hier ihre Offerte ein!</h2>
                <hr class="primary">
            </div>
        </div>
    </div>




  <div class="container">
      <div class="row">
          <div class="col-lg-offset-3 col-lg-6 col-lg-offset-3 text-left">
              <%= simple_form_for @user, url: creatives_create_path do |f| %>
              <%= f.input :first_name, label: "Vorname" %>
              <%= f.input :last_name, label: "Nachname" %>
              <%= f.input :street, label: "Strasse" %>
              <%= f.input :location, label: "Ort" %>
              <%= f.input :plz, label: "Postleitzahl" %>
              <%= f.input :email, label: "Email-Adresse" %>
              <%= f.input :request, label: "Ihre Auftragsbeschreibung", placeholder: "Folgende Leistungen sollen erbracht werden: 30qm Rasen schneiden, 10m Hecke schneiden (manuell), 10qm Kiesweg jäten ...", as: :text, input_html: {style: 'height:160px;'} %>
              <%= f.input :date_delivery, as: :string, input_html: {type: :date}, label: "Wunschtermin" %>
              <%= f.button :submit, "anfragen", :class => "btn-xl btn-primary" %>
              <% end %>
          </div>
      </div>
  </div>

</section>

app/views/creatives/_portfolio.html.erb
<section class="no-padding" id="portfolio">
    <div class="container-fluid">
        <div class="row no-gutter">
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <%= image_tag "creative/portfolio/1.jpg", class: "img-responsive", alt: "" %>
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Category
                            </div>
                            <div class="project-name">
                                Project Name
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <%= image_tag "creative/portfolio/2.jpg", class: "img-responsive", alt: "" %>
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Category
                            </div>
                            <div class="project-name">
                                Project Name
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <%= image_tag "creative/portfolio/3.jpg", class: "img-responsive", alt: "" %>
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Category
                            </div>
                            <div class="project-name">
                                Project Name
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <%= image_tag "creative/portfolio/4.jpg", class: "img-responsive", alt: "" %>
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Category
                            </div>
                            <div class="project-name">
                                Project Name
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <%= image_tag "creative/portfolio/5.jpg", class: "img-responsive", alt: "" %>
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Category
                            </div>
                            <div class="project-name">
                                Project Name
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <%= image_tag "creative/portfolio/6.jpg", class: "img-responsive", alt: "" %>
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Category
                            </div>
                            <div class="project-name">
                                Project Name
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
</section>

app/views/creatives/_services.html.erb
<section id="services">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">Wie funktionierts? Es ist ganz einfach!</h2>
                <hr class="primary">
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-paper-plane wow bounceIn text-primary"></i>
                    <h3>1. Anfrage</h3>
                    <p class="text-muted">Gewünschte Leistung definieren und anfragen</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-search wow bounceIn text-primary" data-wow-delay=".1s"></i>
                    <h3>2. Auswählen</h3>
                    <p class="text-muted">Offerten per Email erhalten und den Favoriten finden</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-handshake-o wow bounceIn text-primary" data-wow-delay=".2s"></i>
                    <h3>3. Buchen</h3>
                    <p class="text-muted">Den Favoriten einfach online buchen</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <i class="fa fa-4x fa-heart wow bounceIn text-primary" data-wow-delay=".3s"></i>
                    <h3>4. Geniessen</h3>
                    <p class="text-muted">Den gemachten Garten geniessen!</p>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/creatives/_thx.html.erb
<section id="services">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">Sie erhalten in Kürze passende Offerten per Email!</h2>
                <hr class="primary">
            </div>
        </div>
    </div>

app/views/creatives/all.html.erb
<% @user.each do |user| %>
    <div class="padded">
      <h5> <%= user.created_at %> </h5>
      <h5> <%= user.email %> </h5>
      <h5> <%= user.first_name %> </h5>
      <h5> <%= user.last_name %> </h5>
      <h5> <%= user.request %> </h5>
      <h5> <%= user.date_delivery  %> </h5>
    </div>
<% end %>

app/views/creatives/end.html.erb
<%= render 'navbar' %>
<%= render 'thx' %>
<%= render 'contact' %>

app/views/creatives/ending.html.erb
<%= render 'navbar' %>
<%= render 'thx' %>
<%= render 'contact' %>

app/views/creatives/index.html.erb
<%= render 'navbar' %>
<%= render 'header' %>
<%= render 'bg_primary' %>
<%= render 'services' %>
<%= render 'call_to_action' %>
<%= render 'contact' %>

app/views/creatives/show.html.erb
<%= render 'navbar' %>
<%= render 'offer' %>
<%= render 'contact' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mapen - finde deinen Gärtner</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/creative.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mapen - finde deinen Gärtner</title>
   <meta name="description" content="Offerten von Gärtnern in der Region einholen">
  <%= stylesheet_link_tag 'creative/manifest.css', media: 'all' %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'creative/manifest.js' %>
  <%= csrf_meta_tags %>

 <!-- Global site tag (gtag.js) - Google AdWords: 854176148 -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=AW-854176148"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'AW-854176148');
  </script>

    <!-- Event snippet for Click on &#39;offerte anfragen&#39; conversion page
  In your html page, add the snippet and call gtag_report_conversion when someone clicks on the chosen link or button. -->
  <script>
  function gtag_report_conversion(url) {
    var callback = function () {
      if (typeof(url) != 'undefined') {
        window.location = url;
      }
    };
    gtag('event', 'conversion', {
        'send_to': 'AW-854176148/4V9RCPvVmngQlOOmlwM',
        'event_callback': callback
    });
    return false;
  }
  </script>

</head>

<body>

<%= yield %>

</body>
</html>